title: HWFWM Wiki
description: A fanmade character wiki for the webnovel 'HWFWM' by Shirtaloon
baseurl: "/Wiki" # site's subpath
url: "" # site's base hostname & protocol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
